name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 6 * * 1-5'

jobs:
  eslint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
      actions: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install eslint@latest
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: |
          npx eslint . \
            --config eslint.config.js \
            --ext .js,.jsx,.ts,.tsx \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif \
        continue-on-error: true

      - name: Debug ESLint output
        run: |
          ls -la
          cat eslint-results.sarif || echo "SARIF file not found"

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true